language: generic  

sudo: required
services:
  - docker

before_install:
  - docker build -t hhoutum/docker-react -f Dockerfile.dev ,
   
script:
   - docker run -e CI=true hhoutum/docker-react npm run test -- --coverage

