FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN mkdir -p /app/node_modules
#RUN chown -R node /app/node_modules
RUN npm install

COPY . .
RUN chown -R node /app/node_modules

USER node
CMD ["npm", "run", "start"]

